In [38]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
df=pd.read_csv(r'../Data/Daily_Activity_2022_27_02.csv')

In [40]:
df.head()

,Id,ActivityDate,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Unnamed: 16,Unnamed: 17
0,1503960366,4/12/2016,Tue,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,NaN,Tue
1,1503960366,4/13/2016,Wed,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,NaN,Wed
2,1503960366,4/14/2016,Thu,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,NaN,Thu
3,1503960366,4/15/2016,Fri,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,NaN,Fri
4,1503960366,4/16/2016,Sat,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,NaN,Sat

In [41]:
df=df.drop('Id',axis=1)
df=df.drop('ActivityDate',axis=1)

In [42]:
df.head()

,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,Unnamed: 16,Unnamed: 17
0,Tue,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,NaN,Tue
1,Wed,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,NaN,Wed
2,Thu,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,NaN,Thu
3,Fri,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,NaN,Fri
4,Sat,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,NaN,Sat

In [43]:
df=df.drop('Unnamed: 16',axis=1)

In [44]:
df=df.drop('Unnamed: 17',axis=1)

In [45]:
df.head()

,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,Tue,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,Wed,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,Thu,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,Fri,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,Sat,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [46]:
df=df.drop_duplicates()

In [47]:
df.isnull()

,ActivityDay,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,False,False,False,False,False,False,False,False,False,False,False,False,False,False
936,False,False,False,False,False,False,False,False,False,False,False,False,False,False
937,False,False,False,False,False,False,False,False,False,False,False,False,False,False
938,False,False,False,False,False,False,False,False,False,False,False,False,False,False
939,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [48]:
df.isnull().sum()

ActivityDay                 0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [49]:
df.describe()

,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,7820.954248,5.621264,5.606569,0.110763,1.538693,0.581144,3.420882,0.001645,21.672113,13.889978,197.433551,980.455338,2317.072985
std,5006.679390,3.877075,3.859610,0.627059,2.680320,0.889681,1.997497,0.007430,33.070499,20.113687,106.262773,296.633841,717.999790
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4061.250000,2.770000,2.770000,0.000000,0.000000,0.000000,2.080000,0.000000,0.000000,0.000000,133.250000,728.000000,1832.000000
50%,7624.500000,5.340000,5.340000,0.000000,0.300000,0.255000,3.445000,0.000000,5.000000,7.000000,201.500000,1052.000000,2171.000000
75%,10777.750000,7.750000,7.745000,0.000000,2.127500,0.810000,4.827500,0.000000,33.000000,20.000000,267.000000,1214.750000,2799.000000
max,36019.000000,28.030001,28.030001,4.942142,21.920000,6.480000,10.710000,0.110000,210.000000,143.000000,518.000000,1440.000000,4900.000000

In [50]:
df.isnull().sum()

ActivityDay                 0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [52]:
df.dtypes

ActivityDay                  object
TotalSteps                    int64
TotalDistance               float64
TrackerDistance             float64
LoggedActivitiesDistance    float64
VeryActiveDistance          float64
ModeratelyActiveDistance    float64
LightActiveDistance         float64
SedentaryActiveDistance     float64
VeryActiveMinutes             int64
FairlyActiveMinutes           int64
LightlyActiveMinutes          int64
SedentaryMinutes              int64
Calories                      int64
dtype: object

In [ ]:
df.head()

In [ ]:
corr=df.corr()

In [ ]:
sns.heatmap(corr)

In [ ]:
dummies=pd.get_dummies(df[['TotalSteps']],drop_first=True)
data_to_be_scaled=df.drop(['TotalSteps'],axis=1)

df_feat=data_to_be_scaled

In [58]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(df_feat)

df_scaled=scaler.transform(df_feat)
df_scaled=pd.DataFrame(df_scaled,columns=df_feat.columns[2])
df=pd.concat([df_scaled,dummies],axis=1)
df.head()

ValueError: could not convert string to float: 'Tue'